# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(0, 0, 811, 591))
        self.Tab.setObjectName("Tab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.layoutWidget = QtWidgets.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sourceLb = QtWidgets.QLabel(self.layoutWidget)
        self.sourceLb.setObjectName("sourceLb")
        self.gridLayout.addWidget(self.sourceLb, 0, 1, 1, 1)
        self.hisLb = QtWidgets.QLabel(self.layoutWidget)
        self.hisLb.setObjectName("hisLb")
        self.gridLayout.addWidget(self.hisLb, 0, 2, 1, 1)
        self.sourceView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.sourceView.setObjectName("sourceView")
        self.gridLayout.addWidget(self.sourceView, 1, 1, 1, 1)
        self.histView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.histView.setObjectName("histView")
        self.gridLayout.addWidget(self.histView, 1, 2, 1, 1)
        self.otsuLb = QtWidgets.QLabel(self.layoutWidget)
        self.otsuLb.setObjectName("otsuLb")
        self.gridLayout.addWidget(self.otsuLb, 2, 1, 1, 1)
        self.entLb = QtWidgets.QLabel(self.layoutWidget)
        self.entLb.setObjectName("entLb")
        self.gridLayout.addWidget(self.entLb, 2, 2, 1, 1)
        self.otsuView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.otsuView.setObjectName("otsuView")
        self.gridLayout.addWidget(self.otsuView, 3, 1, 1, 1)
        self.entropyView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.entropyView.setObjectName("entropyView")
        self.gridLayout.addWidget(self.entropyView, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.threshSlider = QtWidgets.QSlider(self.groupBox)
        self.threshSlider.setGeometry(QtCore.QRect(10, 190, 71, 22))
        self.threshSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threshSlider.setObjectName("threshSlider")
        self.chooseImgBtn = QtWidgets.QPushButton(self.groupBox)
        self.chooseImgBtn.setGeometry(QtCore.QRect(10, 150, 71, 23))
        self.chooseImgBtn.setObjectName("chooseImgBtn")
        self.histBtn = QtWidgets.QPushButton(self.groupBox)
        self.histBtn.setGeometry(QtCore.QRect(10, 230, 71, 23))
        self.histBtn.setIconSize(QtCore.QSize(10, 10))
        self.histBtn.setObjectName("histBtn")
        self.otsuBtn = QtWidgets.QPushButton(self.groupBox)
        self.otsuBtn.setGeometry(QtCore.QRect(10, 270, 71, 23))
        self.otsuBtn.setObjectName("otsuBtn")
        self.entBtn = QtWidgets.QPushButton(self.groupBox)
        self.entBtn.setGeometry(QtCore.QRect(10, 310, 71, 23))
        self.entBtn.setObjectName("entBtn")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 4, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout.setColumnStretch(2, 4)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 10)
        self.Tab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.pushButton = QtWidgets.QPushButton(self.tab2)
        self.pushButton.setGeometry(QtCore.QRect(230, 220, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.Tab.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.label = QtWidgets.QLabel(self.tab3)
        self.label.setGeometry(QtCore.QRect(320, 270, 371, 201))
        self.label.setObjectName("label")
        self.Tab.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab4)
        self.graphicsView.setGeometry(QtCore.QRect(280, 270, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.Tab.addTab(self.tab4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sourceLb.setText(_translate("MainWindow", "SourceImg"))
        self.hisLb.setText(_translate("MainWindow", "Histogram"))
        self.otsuLb.setText(_translate("MainWindow", "OTSU"))
        self.entLb.setText(_translate("MainWindow", "ENTEOPY"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.chooseImgBtn.setText(_translate("MainWindow", "加载源图"))
        self.histBtn.setText(_translate("MainWindow", "Histo"))
        self.otsuBtn.setText(_translate("MainWindow", "OTSU"))
        self.entBtn.setText(_translate("MainWindow", "ENTROPY"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.label.setText(_translate("MainWindow", "姑娘我很棒！"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab3), _translate("MainWindow", "Tab3"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab4), _translate("MainWindow", "Tab4"))

